# Generated by Django 4.2.4 on 2023-09-27 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, help_text='聊天内容', max_length=1000, null=True)),
                ('role', models.IntegerField(default=0, help_text='0代表用户，1代表chatgpt,2代表系统')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='聊天内容创建时间')),
            ],
            options={
                'verbose_name': '聊天内容',
                'verbose_name_plural': '聊天内容',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='聊天标题', max_length=20)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='对话创建时间')),
            ],
            options={
                'verbose_name': '对话',
                'verbose_name_plural': '对话',
                'ordering': ['-created_time'],
            },
        ),
    ]
