# Generated by Django 4.2.4 on 2023-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('system', 'system'), ('assistant', 'assistant')], max_length=12),
        ),
    ]
