# Generated by Django 4.2.4 on 2023-10-03 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatgpt', '0003_alter_chatcontent_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatcontent',
            options={'ordering': ['timestamp'], 'verbose_name': '聊天内容', 'verbose_name_plural': '聊天内容'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-timestamp'], 'verbose_name': '对话', 'verbose_name_plural': '对话'},
        ),
        migrations.RemoveField(
            model_name='chatcontent',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='created_time',
        ),
        migrations.AddField(
            model_name='chatcontent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='聊天内容创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='对话创建时间'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='使用时间')),
                ('prompt_tokens', models.IntegerField(default=0, help_text='发送内容的token数')),
                ('completion_tokens', models.IntegerField(default=0, help_text='返回内容的token数')),
                ('user', models.ForeignKey(help_text='用户外键', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
