# Generated by Django 4.2.4 on 2023-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0004_alter_chatcontent_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', help_text='聊天标题', max_length=50),
        ),
    ]
