# Generated by Django 4.2.4 on 2023-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0005_alter_conversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='content',
            field=models.CharField(default=None, help_text='聊天内容', max_length=4096, null=True),
        ),
    ]
