# Generated by Django 4.2.4 on 2023-10-12 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userassets_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='反馈创建时间')),
                ('handled', models.BooleanField(default=False, help_text='是否已经处理')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedback_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='反馈创建时间')),
                ('handled', models.BooleanField(default=False, help_text='是否已经处理')),
                ('feedback', models.ForeignKey(help_text='所属反馈', on_delete=django.db.models.deletion.CASCADE, to='users.feedback')),
                ('user', models.ForeignKey(help_text='所属用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '反馈的回复',
                'verbose_name_plural': '反馈的回复',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='images',
            field=models.ManyToManyField(blank=True, to='users.feedbackimage'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(help_text='所属用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
