# Generated by Django 4.2.4 on 2023-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback_feedbackimage_feedbackreply_feedback_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassets',
            name='idphoto_count',
            field=models.IntegerField(default=0, help_text='下载证件照剩余使用次数'),
        ),
    ]
