# Generated by Django 4.2.4 on 2023-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('api_name', models.CharField(max_length=30)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('parameters', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField()),
                ('response_data', models.CharField(max_length=512)),
                ('processing_time', models.DurationField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
