# Generated by Django 4.2.4 on 2023-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesslog',
            name='processing_time',
            field=models.IntegerField(help_text='api处理时间，单位ms'),
        ),
    ]
