# Generated by Django 4.2.4 on 2023-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0002_alter_apiaccesslog_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesslog',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
