# Generated by Django 4.2.4 on 2023-10-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0003_alter_apiaccesslog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesslog',
            name='response_data',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
