# Generated by Django 4.2.4 on 2023-11-14 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_pic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photourls',
            old_name='maketime',
            new_name='createtime',
        ),
        migrations.RemoveField(
            model_name='photourls',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='photourls',
            name='username',
        ),
        migrations.AddField(
            model_name='photourls',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='id_photo/'),
        ),
        migrations.AddField(
            model_name='photourls',
            name='user',
            field=models.ForeignKey(default=1, help_text='所属用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FeedbackImage',
        ),
    ]
