# Generated by Django 4.2.4 on 2023-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pic', '0002_rename_maketime_photourls_createtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photourls',
            name='watermarkerimage',
            field=models.ImageField(blank=True, null=True, upload_to='id_photo/'),
        ),
    ]
